### ISSUE TITLE
DX7 - Blockchain Hyperledger Fabric Plugin (joget-hyperledger-fabric-6.2.1.jar) - Error uploading plugin

### ISSUE THREAD

**Issue by pasarmaya** [jogetoss/joget-hyperledger-fabric#1]
Blockchain Hyperledger Fabric Plugin joget-hyperledger-fabric-6.2.1.jar - Error uploading plugin

Dear Joget Hyperledger Fabric Plugin developer,

I tried to upload joget-hyperledger-fabric-6.2.1.jar on DX 7, but failed.
Error message: "Error uploading plugin"

We were following this reference: https://dev.joget.org/community/display/DX7/Blockchain+Hyperledger+Fabric+Plugins
Please check the plugin: Blockchain Hyperledger Fabric Plugins

Waiting for your advice.

Big Tx.

references:
https://dev.joget.org/community/display/DX7/questions/161710185/blockchain-hyperledger-fabric-plugin-joget-hyperledger-fabric-6.2.1.jar---error-uploading-plugin

**Comment by juljog** [comment]
Hi there, 

Thanks for reporting this issue. Please try the latest version of the plugin at https://dev.joget.org/community/display/DX7/Blockchain+Hyperledger+Fabric+Plugins.
